<?php

/**
 * Model_Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Model_Post extends Model_Base_Post
{
    public function getAuthorName() {
        $author = $this->Author;
        
        return $author->first_name . ' ' . $author->last_name;
    }
}